### PR TITLE
fix(rgbpp-sdk/btc): duplicate inputs in TxBuilder

### LINKED ISSUE #69: -26 when referencing rgbpp-lock cells with the same lock args
Dylan found an issue when creating BTC_TX from CKB_TX. If the inputs of the CKB_TX include multiple cells that bind to the same UTXO on BTC, the BTC_TX construction process just adds them without checking. In other words, those inputs share the exact same rgbpp-lock (including lock args).

This causes a `bad-txns-inputs-duplicate` (-26) error on the BTC RPC.

## Related PR
- https://github.com/ckb-cell/rgbpp-sdk/pull/67

### PR DESCRIPTION
**Pull request by ShookLyngs**
## Changes
- Fixes #69 

## Exmaple

Generated 2 RGBPP cells bind to the same [UTXO](https://mempool.space/testnet/tx/4ebb27e484f81acb8f33e642bc05ef70308678e1c312352e44f2183d492874b8). 
Each cell has 10 UDT and they have 20 UDT in total.

- [Cell#1](https://pudge.explorer.nervos.org/transaction/0xdfba92b05a7781a86dd55d63ecc7a6e81acd5680f84ddecd1fcb3059b211f09e): contains 10 UDT
- [Cell#2](https://pudge.explorer.nervos.org/transaction/0xea15296b575e52035b1136ab92b0b9dac3d46c76fd037c27908e875635834a60): contains 10 UDT

And then, transfer 20 UDT (with the L1->L1 Transfer example):

- [CKB TX](https://pudge.explorer.nervos.org/transaction/0xce1c4b30a66ebd975c7093f2859c4661dd6ad91d649c781da12629ce70475f49): The Cell#1 and Cell#2 are included in the inputs of the CKB TX. The two cells share the same lock script (including args), meaning they're bind to the same UTXO.
- [BTC TX](https://mempool.space/testnet/tx/ca5d3b328f6fc6d5f624b775ef2f3060cdf6b11875f4f37cd8cbc4883a690a2b):   No duplicated error triggered during the construction process, the referenced RGBPP UTXO was included in the vin of the transaction once.

### CODE REVIEW

File: packages/btc/src/api/sendRgbppUtxos.ts [hunk 1]
```diff
@@ -64,6 +65,11 @@ export async function sendRgbppUtxos(props: {
         throw new TxBuildError(ErrorCodes.REFERENCED_UNPROVABLE_UTXO);
       }
 
+      const foundInInputs = inputs.some((v) => v.txid === utxo.txid && v.vout === utxo.vout);
```
Comment (duanyytop) [inline packages/btc/src/api/sendRgbppUtxos.ts:68]: I think the `foundInInputs` will always true

**Review by duanyytop — APPROVED** [review]

**Review by Flouse — APPROVED** [review]
